[build]
base = "ubuntu-22.04"

[build.environment]
NODE_VERSION = "20.19.0"

[phases.setup]
nixPkgs = ["nodejs-20.19.0"]

[phases.build]
commands = ["echo 'Skipping build - using pre-built assets'"]

[phases.start]
commands = ["./railway-deploy.sh"]