[build]
builder = "nixpacks"
buildCommand = "echo 'Using pre-built assets from repository'"

[deploy]
startCommand = "chmod +x railway-deploy.sh && ./railway-deploy.sh"
restartPolicyType = "ON_FAILURE"

[environment]
NODE_VERSION = "20.19.0"